//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoServiceGoncharovUP01
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestLog
    {
        public int log_id { get; set; }
        public Nullable<int> request_id { get; set; }
        public Nullable<System.DateTime> date_changed { get; set; }
        public string comment { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
